# Generated by Django 4.2.5 on 2023-09-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=1000)),
                ('about', models.CharField(max_length=1000)),
                ('process', models.CharField(max_length=1000)),
                ('remarks', models.CharField(max_length=1000)),
                ('benefits', models.CharField(max_length=1000)),
                ('questionsToAsk', models.CharField(max_length=1000)),
                ('technicalSkills', models.CharField(max_length=1000)),
                ('softSkills', models.CharField(max_length=1000)),
                ('cultureFit', models.CharField(max_length=1000)),
                ('helpfulLinks', models.CharField(max_length=1000)),
                ('commonQuestions', models.CharField(max_length=100)),
            ],
        ),
    ]
