# Generated by Django 4.2.5 on 2023-09-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_remove_todo_benefits_remove_todo_commonquestions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='companyBenefits',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AddField(
            model_name='todo',
            name='cultureFit',
            field=models.CharField(default='casual', max_length=1000),
        ),
        migrations.AddField(
            model_name='todo',
            name='helpfulLinks',
            field=models.CharField(default='company website', max_length=1000),
        ),
        migrations.AddField(
            model_name='todo',
            name='questionsToAnswer',
            field=models.CharField(default='what would the interviewer ask you', max_length=1000),
        ),
        migrations.AddField(
            model_name='todo',
            name='questionsToAsk',
            field=models.CharField(default='what would you like to ask the interviewer', max_length=1000),
        ),
        migrations.AddField(
            model_name='todo',
            name='remarks',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AddField(
            model_name='todo',
            name='softSkills',
            field=models.CharField(default='people skills', max_length=1000),
        ),
        migrations.AddField(
            model_name='todo',
            name='technicalSkills',
            field=models.CharField(default='DSA', max_length=1000),
        ),
    ]
